# Generated by Django 3.2.10 on 2023-08-03 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 8 characters')])),
                ('bio', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=1000)),
                ('random_string', models.CharField(max_length=1000)),
                ('verified', models.BooleanField()),
            ],
        ),
    ]
